# Generated by Django 3.1 on 2020-09-07 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('AuditID', models.CharField(max_length=45)),
                ('RevisionNumber', models.CharField(max_length=45)),
                ('FacilityName', models.CharField(max_length=100)),
                ('FacilityID', models.CharField(max_length=45)),
                ('Auditor1', models.CharField(max_length=45)),
                ('Auditor2', models.CharField(max_length=45)),
                ('Auditor3', models.CharField(max_length=45)),
                ('AuditDate', models.DateTimeField()),
                ('RepDate', models.CharField(max_length=45)),
                ('LinacModel', models.CharField(max_length=45)),
                ('LinacManufacturer', models.CharField(max_length=45)),
                ('PlanningSystemManufacturer', models.CharField(max_length=45)),
                ('tps', models.CharField(max_length=45)),
                ('Algorithm', models.CharField(max_length=45)),
                ('kqFac', models.CharField(max_length=10)),
                ('ACDS', models.CharField(max_length=10)),
                ('Phantom', models.CharField(max_length=45)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='FacilityOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('energy_6', models.DecimalField(decimal_places=3, max_digits=6)),
                ('energy_10', models.DecimalField(decimal_places=3, max_digits=6)),
                ('energy_15', models.DecimalField(decimal_places=3, max_digits=6)),
                ('energy_18', models.DecimalField(decimal_places=3, max_digits=6)),
                ('energy_6FFF', models.DecimalField(decimal_places=3, max_digits=6)),
                ('energy_10FFF', models.DecimalField(decimal_places=3, max_digits=6)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilityOutput', to='graphs.result')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
