# Generated by Django 3.1 on 2020-09-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='fileName',
            field=models.CharField(default='/user', max_length=250),
            preserve_default=False,
        ),
    ]
