# Generated by Django 3.1 on 2020-09-08 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('energy_6', models.DecimalField(decimal_places=3, max_digits=6)),
                ('energy_10', models.DecimalField(decimal_places=3, max_digits=6)),
                ('energy_15', models.DecimalField(decimal_places=3, max_digits=6)),
                ('energy_18', models.DecimalField(decimal_places=3, max_digits=6)),
                ('energy_6FFF', models.DecimalField(decimal_places=3, max_digits=6)),
                ('energy_10FFF', models.DecimalField(decimal_places=3, max_digits=6)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TPR', to='graphs.result')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
