# Generated by Django 3.1 on 2020-09-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0002_graph_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityoutput',
            name='energy_10',
            field=models.DecimalField(decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='facilityoutput',
            name='energy_10FFF',
            field=models.DecimalField(decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='facilityoutput',
            name='energy_15',
            field=models.DecimalField(decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='facilityoutput',
            name='energy_18',
            field=models.DecimalField(decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='facilityoutput',
            name='energy_6',
            field=models.DecimalField(decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='facilityoutput',
            name='energy_6FFF',
            field=models.DecimalField(decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='AuditDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tpr',
            name='energy_10',
            field=models.DecimalField(decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='tpr',
            name='energy_10FFF',
            field=models.DecimalField(decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='tpr',
            name='energy_15',
            field=models.DecimalField(decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='tpr',
            name='energy_18',
            field=models.DecimalField(decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='tpr',
            name='energy_6',
            field=models.DecimalField(decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='tpr',
            name='energy_6FFF',
            field=models.DecimalField(decimal_places=4, max_digits=7, null=True),
        ),
    ]
