# Generated by Django 3.1 on 2020-09-08 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0003_reading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Misdelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('Misdelivery_101106', models.SmallIntegerField(max_length=1)),
                ('Misdelivery_110106', models.SmallIntegerField(max_length=1)),
                ('Misdelivery_205106', models.SmallIntegerField(max_length=1)),
                ('Misdelivery_208106', models.SmallIntegerField(max_length=1)),
                ('Misdelivery_205206', models.SmallIntegerField(max_length=1)),
                ('Misdelivery_208206', models.SmallIntegerField(max_length=1)),
                ('Misdelivery_205306', models.SmallIntegerField(max_length=1)),
                ('Misdelivery_208306', models.SmallIntegerField(max_length=1)),
                ('Misdelivery_303106', models.SmallIntegerField(max_length=1)),
                ('Misdelivery_305106', models.SmallIntegerField(max_length=1)),
                ('Misdelivery_403106', models.SmallIntegerField(max_length=1)),
                ('Misdelivery_405106', models.SmallIntegerField(max_length=1)),
                ('Misdelivery_103110', models.SmallIntegerField(max_length=1)),
                ('Misdelivery_110110', models.SmallIntegerField(max_length=1)),
                ('Misdelivery_303110', models.SmallIntegerField(max_length=1)),
                ('Misdelivery_305110', models.SmallIntegerField(max_length=1)),
                ('Misdelivery_403110', models.SmallIntegerField(max_length=1)),
                ('Misdelivery_405110', models.SmallIntegerField(max_length=1)),
                ('Misdelivery_103115', models.SmallIntegerField(max_length=1)),
                ('Misdelivery_110115', models.SmallIntegerField(max_length=1)),
                ('Misdelivery_303115', models.SmallIntegerField(max_length=1)),
                ('Misdelivery_305115', models.SmallIntegerField(max_length=1)),
                ('Misdelivery_403115', models.SmallIntegerField(max_length=1)),
                ('Misdelivery_405115', models.SmallIntegerField(max_length=1)),
                ('Misdelivery_103118', models.SmallIntegerField(max_length=1)),
                ('Misdelivery_110118', models.SmallIntegerField(max_length=1)),
                ('Misdelivery_303118', models.SmallIntegerField(max_length=1)),
                ('Misdelivery_305118', models.SmallIntegerField(max_length=1)),
                ('Misdelivery_403118', models.SmallIntegerField(max_length=1)),
                ('Misdelivery_405118', models.SmallIntegerField(max_length=1)),
                ('Misdelivery_101105', models.SmallIntegerField(max_length=1)),
                ('Misdelivery_110105', models.SmallIntegerField(max_length=1)),
                ('Misdelivery_303105', models.SmallIntegerField(max_length=1)),
                ('Misdelivery_305105', models.SmallIntegerField(max_length=1)),
                ('Misdelivery_103109', models.SmallIntegerField(max_length=1)),
                ('Misdelivery_110109', models.SmallIntegerField(max_length=1)),
                ('Misdelivery_303109', models.SmallIntegerField(max_length=1)),
                ('Misdelivery_305109', models.SmallIntegerField(max_length=1)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Misdelivery', to='graphs.result')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
