# Generated by Django 3.1 on 2020-10-04 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0004_imrt'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMRT_misdelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('c6_p11_6', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c6_p12_6', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c6_p13_6', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c6_p14_6', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c6_p15_6', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c6_p16_6', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c6_p17_6', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c7_p11_6', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c7_p12_6', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c7_p13_6', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c7_p14_6', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c7_p15_6', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c7_p16_6', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c7_p17_6', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c8_p11_6', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c8_p12_6', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c8_p13_6', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c8_p14_6', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c8_p15_6', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c8_p17_6', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c8_p18_6', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c6_p11_10', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c6_p12_10', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c6_p13_10', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c6_p14_10', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c6_p15_10', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c6_p16_10', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c6_p17_10', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c7_p11_10', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c7_p12_10', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c7_p13_10', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c7_p14_10', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c7_p15_10', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c7_p16_10', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c7_p17_10', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c8_p11_10', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c8_p12_10', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c8_p13_10', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c8_p14_10', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c8_p15_10', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c8_p17_10', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('c8_p18_10', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IMRT_misdelivery', to='graphs.result')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
