# Generated by Django 3.1 on 2020-09-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0009_auto_20200914_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='url',
            field=models.CharField(max_length=250),
        ),
    ]
