# Generated by Django 3.1 on 2020-09-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('AuditID', models.CharField(max_length=45)),
                ('RevisionNumber', models.CharField(max_length=45)),
                ('FacilityName', models.CharField(max_length=100)),
                ('FacilityID', models.CharField(max_length=45)),
                ('Auditor1', models.CharField(max_length=45)),
                ('Auditor2', models.CharField(max_length=45)),
                ('Auditor3', models.CharField(max_length=45)),
                ('AuditDate', models.DateTimeField()),
                ('RepDate', models.CharField(max_length=45)),
                ('LinacModel', models.CharField(max_length=45)),
                ('LinacManufacturer', models.CharField(max_length=45)),
                ('PlanningSystemManufacturer', models.CharField(max_length=45)),
                ('tps', models.CharField(max_length=45)),
                ('Algorithm', models.CharField(max_length=45)),
                ('kqFac', models.CharField(max_length=10)),
                ('ACDS', models.CharField(max_length=10)),
                ('Phantom', models.CharField(max_length=45)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
