# Generated by Django 3.1 on 2020-09-08 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0002_tpr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('Reading_101106', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Reading_110106', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Reading_205106', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Reading_208106', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Reading_205206', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Reading_208206', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Reading_205306', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Reading_208306', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Reading_303106', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Reading_305106', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Reading_403106', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Reading_405106', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Reading_103110', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Reading_110110', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Reading_303110', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Reading_305110', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Reading_403110', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Reading_405110', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Reading_103115', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Reading_110115', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Reading_303115', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Reading_305115', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Reading_403115', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Reading_405115', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Reading_103118', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Reading_110118', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Reading_303118', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Reading_305118', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Reading_403118', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Reading_405118', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Reading_101105', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Reading_110105', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Reading_303105', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Reading_305105', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Reading_103109', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Reading_110109', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Reading_303109', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Reading_305109', models.DecimalField(decimal_places=2, max_digits=5)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reading', to='graphs.result')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
