# Generated by Django 3.1 on 2020-09-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0007_graph_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misdelivery',
            name='Misdelivery_101105',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='misdelivery',
            name='Misdelivery_101106',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='misdelivery',
            name='Misdelivery_103109',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='misdelivery',
            name='Misdelivery_103110',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='misdelivery',
            name='Misdelivery_103115',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='misdelivery',
            name='Misdelivery_103118',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='misdelivery',
            name='Misdelivery_110105',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='misdelivery',
            name='Misdelivery_110106',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='misdelivery',
            name='Misdelivery_110109',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='misdelivery',
            name='Misdelivery_110110',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='misdelivery',
            name='Misdelivery_110115',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='misdelivery',
            name='Misdelivery_110118',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='misdelivery',
            name='Misdelivery_205106',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='misdelivery',
            name='Misdelivery_205206',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='misdelivery',
            name='Misdelivery_205306',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='misdelivery',
            name='Misdelivery_208106',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='misdelivery',
            name='Misdelivery_208206',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='misdelivery',
            name='Misdelivery_208306',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='misdelivery',
            name='Misdelivery_303105',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='misdelivery',
            name='Misdelivery_303106',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='misdelivery',
            name='Misdelivery_303109',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='misdelivery',
            name='Misdelivery_303110',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='misdelivery',
            name='Misdelivery_303115',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='misdelivery',
            name='Misdelivery_303118',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='misdelivery',
            name='Misdelivery_305105',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='misdelivery',
            name='Misdelivery_305106',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='misdelivery',
            name='Misdelivery_305109',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='misdelivery',
            name='Misdelivery_305110',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='misdelivery',
            name='Misdelivery_305115',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='misdelivery',
            name='Misdelivery_305118',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='misdelivery',
            name='Misdelivery_403106',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='misdelivery',
            name='Misdelivery_403110',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='misdelivery',
            name='Misdelivery_403115',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='misdelivery',
            name='Misdelivery_403118',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='misdelivery',
            name='Misdelivery_405106',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='misdelivery',
            name='Misdelivery_405110',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='misdelivery',
            name='Misdelivery_405115',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='misdelivery',
            name='Misdelivery_405118',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='Reading_101105',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='Reading_101106',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='Reading_103109',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='Reading_103110',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='Reading_103115',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='Reading_103118',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='Reading_110105',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='Reading_110106',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='Reading_110109',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='Reading_110110',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='Reading_110115',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='Reading_110118',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='Reading_205106',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='Reading_205206',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='Reading_205306',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='Reading_208106',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='Reading_208206',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='Reading_208306',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='Reading_303105',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='Reading_303106',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='Reading_303109',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='Reading_303110',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='Reading_303115',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='Reading_303118',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='Reading_305105',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='Reading_305106',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='Reading_305109',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='Reading_305110',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='Reading_305115',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='Reading_305118',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='Reading_403106',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='Reading_403110',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='Reading_403115',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='Reading_403118',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='Reading_405106',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='Reading_405110',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='Reading_405115',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='Reading_405118',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='Auditor2',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='Auditor3',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
