version: '3'

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3305:3306"
    environment:
      MYSQL_DATABASE: dockerSampleT
      MYSQL_ROOT_PASSWORD: AA-koala123456
    volumes:
      - /data:/var/lib/mysql

